- name: Check if RKE has been installed
  stat:
    path: /usr/local/lib/systemd/system/rke2-server.service
  register: rke2_server

- name: Install RKE2
  shell: curl -sfL https://get.rke2.io | sh -
  when: not rke2_server.stat.exists

- name: Create RKE2 Config dir
  file:
    path: /etc/rancher/rke2
    state: directory

- name: Copy config.yaml to created dir
  template:
    src: config-server.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: Make required config directory
  file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory

- name: Copy RKE2 resources config files 
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/rancher/rke2/server/manifests/{{ item }}"
  loop:
    - rke2-canal-config.yaml
    - rke2-ingress-config.yaml

- name: Enable RKE2 service
  systemd:
    name: rke2-server
    enabled: true
    state: started

- name: Copy kubectl to bin
  copy:
    src: "/var/lib/rancher/rke2/bin/{{ item }}"
    remote_src: true
    dest: /usr/bin
    owner: root
    group: root
    mode: '0755'
  loop:
    - kubectl
    - crictl
    - ctr

- name: Install Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: Create kubeconfig directory
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy kubeconfig to vagrant user
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/vagrant/.kube/config
    remote_src: true
    mode: '0600'
    owner: vagrant
    group: vagrant

- name: Register node_token variable
  shell: cat /var/lib/rancher/rke2/server/node-token
  register: node_token
